// 25 Master-Crafted Campaign Levels featuring progressive mechanics:
// Multi-segment snakes, Ice barriers, Pivot rotators, Bomb detonators, Deflector dots, and Mask silhouettes.
import type { LevelData } from './types';

export const CAMPAIGN_LEVELS: readonly LevelData[] = [
  // ── PHASE 1: FUNDAMENTALS & MULTI-CELL ARROWS (Levels 1-5) ──────────────
  {
    id: 1,
    name: 'First Steps',
    subtitle: 'Tap the unblocked arrow to launch it free',
    difficulty: 'beginner',
    rows: 3,
    cols: 3,
    parMoves: 3,
    rewardCoins: 50,
    arrows: [
      { id: '1-1', row: 1, col: 0, direction: 'left', color: '#06b6d4' },
      { id: '1-2', row: 1, col: 1, direction: 'left', color: '#3b82f6' },
      { id: '1-3', row: 1, col: 2, direction: 'left', color: '#6366f1' },
    ],
  },
  {
    id: 2,
    name: 'Cross Traffic',
    subtitle: 'Resolve the intersection from outside in',
    difficulty: 'beginner',
    rows: 3,
    cols: 3,
    parMoves: 4,
    rewardCoins: 60,
    arrows: [
      { id: '2-1', row: 0, col: 1, direction: 'up', color: '#10b981' },
      { id: '2-2', row: 1, col: 0, direction: 'left', color: '#06b6d4' },
      { id: '2-3', row: 1, col: 2, direction: 'right', color: '#f59e0b' },
      { id: '2-4', row: 2, col: 1, direction: 'down', color: '#ec4899' },
    ],
  },
  {
    id: 3,
    name: 'Spiral Knot',
    subtitle: 'One key arrow unbinds the clockwise loop',
    difficulty: 'beginner',
    rows: 3,
    cols: 3,
    parMoves: 6,
    rewardCoins: 75,
    arrows: [
      { id: '3-1', row: 0, col: 0, direction: 'right', color: '#8b5cf6' },
      { id: '3-2', row: 0, col: 1, direction: 'down', color: '#3b82f6' },
      { id: '3-3', row: 1, col: 1, direction: 'down', color: '#06b6d4' },
      { id: '3-4', row: 2, col: 1, direction: 'left', color: '#10b981' },
      { id: '3-5', row: 2, col: 0, direction: 'down', color: '#f59e0b' },
      { id: '3-6', row: 0, col: 2, direction: 'right', color: '#ec4899' },
    ],
  },
  {
    id: 4,
    name: 'Diagonal Corridors',
    subtitle: 'Angles slip through diagonal grid channels',
    difficulty: 'easy',
    rows: 4,
    cols: 4,
    parMoves: 8,
    rewardCoins: 90,
    arrows: [
      { id: '4-1', row: 0, col: 0, direction: 'up-left', color: '#06b6d4' },
      { id: '4-2', row: 0, col: 3, direction: 'up-right', color: '#3b82f6' },
      { id: '4-3', row: 3, col: 0, direction: 'down-left', color: '#ec4899' },
      { id: '4-4', row: 3, col: 3, direction: 'down-right', color: '#f59e0b' },
      { id: '4-5', row: 1, col: 1, direction: 'up', color: '#10b981' },
      { id: '4-6', row: 1, col: 2, direction: 'right', color: '#8b5cf6' },
      { id: '4-7', row: 2, col: 1, direction: 'left', color: '#06b6d4' },
      { id: '4-8', row: 2, col: 2, direction: 'down', color: '#f43f5e' },
    ],
  },
  {
    id: 5,
    name: 'Pinwheel Core',
    subtitle: 'Peel away outer layers to access the center',
    difficulty: 'easy',
    rows: 4,
    cols: 4,
    parMoves: 10,
    rewardCoins: 100,
    arrows: [
      { id: '5-1', row: 0, col: 1, direction: 'right', color: '#06b6d4' },
      { id: '5-2', row: 0, col: 2, direction: 'right', color: '#06b6d4' },
      { id: '5-3', row: 1, col: 3, direction: 'down', color: '#3b82f6' },
      { id: '5-4', row: 2, col: 3, direction: 'down', color: '#3b82f6' },
      { id: '5-5', row: 3, col: 2, direction: 'left', color: '#10b981' },
      { id: '5-6', row: 3, col: 1, direction: 'left', color: '#10b981' },
      { id: '5-7', row: 2, col: 0, direction: 'up', color: '#f59e0b' },
      { id: '5-8', row: 1, col: 0, direction: 'up', color: '#f59e0b' },
      { id: '5-9', row: 1, col: 1, direction: 'up-left', color: '#ec4899' },
      { id: '5-10', row: 2, col: 2, direction: 'down-right', color: '#8b5cf6' },
    ],
  },

  // ── PHASE 2: MULTI-SEGMENT SNAKES & ICE BARRIERS (Levels 6-10) ───────────
  {
    id: 6,
    name: 'Twin Serpents',
    subtitle: 'Elongated arrows pull their entire body along',
    difficulty: 'easy',
    rows: 4,
    cols: 4,
    parMoves: 5,
    rewardCoins: 110,
    arrows: [
      // Serpent 1: length 2 moving up
      {
        id: '6-1',
        direction: 'up',
        head: { row: 0, col: 1 },
        occupiedCells: [{ row: 0, col: 1 }, { row: 1, col: 1 }],
        color: '#06b6d4',
      },
      // Serpent 2: length 2 moving down
      {
        id: '6-2',
        direction: 'down',
        head: { row: 3, col: 2 },
        occupiedCells: [{ row: 3, col: 2 }, { row: 2, col: 2 }],
        color: '#ec4899',
      },
      { id: '6-3', row: 0, col: 0, direction: 'left', color: '#10b981' },
      { id: '6-4', row: 3, col: 3, direction: 'right', color: '#f59e0b' },
      { id: '6-5', row: 1, col: 3, direction: 'up', color: '#8b5cf6' },
    ],
  },
  {
    id: 7,
    name: 'L-Turn Alley',
    subtitle: 'Snake arrows can wrap around orthogonal corners',
    difficulty: 'medium',
    rows: 4,
    cols: 4,
    parMoves: 6,
    rewardCoins: 125,
    arrows: [
      // Corner snake L: head (0,0) facing up, body (1,0) and (1,1)
      {
        id: '7-1',
        direction: 'up',
        head: { row: 0, col: 0 },
        occupiedCells: [{ row: 0, col: 0 }, { row: 1, col: 0 }, { row: 1, col: 1 }],
        color: '#3b82f6',
      },
      // Corner snake L: head (3,3) facing down, body (2,3) and (2,2)
      {
        id: '7-2',
        direction: 'down',
        head: { row: 3, col: 3 },
        occupiedCells: [{ row: 3, col: 3 }, { row: 2, col: 3 }, { row: 2, col: 2 }],
        color: '#10b981',
      },
      { id: '7-3', row: 0, col: 2, direction: 'right', color: '#f59e0b' },
      { id: '7-4', row: 3, col: 1, direction: 'left', color: '#ec4899' },
      { id: '7-5', row: 0, col: 3, direction: 'up', color: '#06b6d4' },
      { id: '7-6', row: 3, col: 0, direction: 'down', color: '#8b5cf6' },
    ],
  },
  {
    id: 8,
    name: 'Frozen Citadel',
    subtitle: 'Tap the frozen arrow to shatter its ice shell',
    difficulty: 'medium',
    rows: 4,
    cols: 4,
    parMoves: 6,
    rewardCoins: 140,
    arrows: [
      // Frozen arrow guarding lane
      {
        id: '8-1',
        row: 1,
        col: 1,
        direction: 'up',
        color: '#06b6d4',
        isFrozen: true,
        frozenHits: 1,
      },
      { id: '8-2', row: 2, col: 1, direction: 'up', color: '#3b82f6' },
      { id: '8-3', row: 1, col: 2, direction: 'right', color: '#10b981' },
      { id: '8-4', row: 2, col: 2, direction: 'down', color: '#ec4899' },
      { id: '8-5', row: 0, col: 3, direction: 'right', color: '#f59e0b' },
    ],
  },
  {
    id: 9,
    name: 'Double Frost',
    subtitle: 'Multiple ice barriers lock adjacent flight corridors',
    difficulty: 'medium',
    rows: 4,
    cols: 4,
    parMoves: 7,
    rewardCoins: 150,
    arrows: [
      { id: '9-1', row: 0, col: 1, direction: 'up', color: '#06b6d4', isFrozen: true, frozenHits: 1 },
      { id: '9-2', row: 3, col: 2, direction: 'down', color: '#3b82f6', isFrozen: true, frozenHits: 1 },
      { id: '9-3', row: 1, col: 1, direction: 'up', color: '#10b981' },
      { id: '9-4', row: 2, col: 2, direction: 'down', color: '#ec4899' },
      { id: '9-5', row: 1, col: 0, direction: 'left', color: '#f59e0b' },
      { id: '9-6', row: 2, col: 3, direction: 'right', color: '#8b5cf6' },
      { id: '9-7', row: 0, col: 0, direction: 'left', color: '#06b6d4' },
    ],
  },
  {
    id: 10,
    name: 'Permafrost Vault',
    subtitle: 'Heavy ice blocks require 2 taps to break completely',
    difficulty: 'medium',
    rows: 5,
    cols: 5,
    parMoves: 9,
    rewardCoins: 175,
    arrows: [
      { id: '10-1', row: 2, col: 2, direction: 'right', color: '#06b6d4', isFrozen: true, frozenHits: 2 },
      { id: '10-2', row: 2, col: 1, direction: 'right', color: '#3b82f6' },
      { id: '10-3', row: 1, col: 2, direction: 'up', color: '#10b981' },
      { id: '10-4', row: 3, col: 2, direction: 'down', color: '#ec4899' },
      { id: '10-5', row: 0, col: 2, direction: 'up', color: '#f59e0b' },
      { id: '10-6', row: 4, col: 2, direction: 'down', color: '#8b5cf6' },
      { id: '10-7', row: 2, col: 0, direction: 'left', color: '#10b981' },
      { id: '10-8', row: 2, col: 4, direction: 'right', color: '#06b6d4' },
    ],
  },

  // ── PHASE 3: PIVOTS, BOMBS & DEFLECTORS (Levels 11-15) ───────────────────
  {
    id: 11,
    name: 'The Compass Pivot',
    subtitle: 'Pivot arrows turn 90° clockwise on tap to find an open escape',
    difficulty: 'medium',
    rows: 4,
    cols: 4,
    parMoves: 6,
    rewardCoins: 185,
    arrows: [
      // Pivot arrow starting pointing down into blocker (2,1)
      { id: '11-1', row: 1, col: 1, direction: 'down', color: '#f59e0b', isPivot: true },
      { id: '11-2', row: 2, col: 1, direction: 'down', color: '#06b6d4' },
      { id: '11-3', row: 1, col: 0, direction: 'left', color: '#10b981' },
      { id: '11-4', row: 0, col: 1, direction: 'up', color: '#ec4899' },
      { id: '11-5', row: 2, col: 2, direction: 'right', color: '#8b5cf6' },
    ],
  },
  {
    id: 12,
    name: 'Turntable Junction',
    subtitle: 'Rotate paired pivots to redirect surrounding flow',
    difficulty: 'hard',
    rows: 4,
    cols: 4,
    parMoves: 7,
    rewardCoins: 200,
    arrows: [
      { id: '12-1', row: 1, col: 1, direction: 'right', color: '#f59e0b', isPivot: true },
      { id: '12-2', row: 2, col: 2, direction: 'left', color: '#f59e0b', isPivot: true },
      { id: '12-3', row: 0, col: 1, direction: 'up', color: '#06b6d4' },
      { id: '12-4', row: 3, col: 2, direction: 'down', color: '#3b82f6' },
      { id: '12-5', row: 1, col: 3, direction: 'right', color: '#10b981' },
      { id: '12-6', row: 2, col: 0, direction: 'left', color: '#ec4899' },
    ],
  },
  {
    id: 13,
    name: 'Bomb Squad',
    subtitle: 'Tap the bomb arrow to detonate and vaporize surrounding obstacles',
    difficulty: 'hard',
    rows: 5,
    cols: 5,
    parMoves: 7,
    rewardCoins: 220,
    arrows: [
      // Central bomb arrow
      { id: 13 + '-bomb', row: 2, col: 2, direction: 'up', color: '#f43f5e', isBomb: true },
      // Surrounding cluster
      { id: '13-1', row: 1, col: 2, direction: 'down', color: '#06b6d4' },
      { id: '13-2', row: 3, col: 2, direction: 'up', color: '#3b82f6' },
      { id: '13-3', row: 2, col: 1, direction: 'right', color: '#10b981' },
      { id: '13-4', row: 2, col: 3, direction: 'left', color: '#ec4899' },
      // Outer unblocked arrows
      { id: '13-5', row: 0, col: 0, direction: 'up-left', color: '#f59e0b' },
      { id: '13-6', row: 4, col: 4, direction: 'down-right', color: '#8b5cf6' },
    ],
  },
  {
    id: 14,
    name: 'Chain Reaction',
    subtitle: 'Detonate strategically to clear heavy permafrost',
    difficulty: 'hard',
    rows: 5,
    cols: 5,
    parMoves: 8,
    rewardCoins: 240,
    arrows: [
      { id: '14-bomb', row: 2, col: 1, direction: 'right', color: '#f43f5e', isBomb: true },
      { id: '14-1', row: 2, col: 2, direction: 'right', color: '#06b6d4', isFrozen: true, frozenHits: 2 },
      { id: '14-2', row: 1, col: 1, direction: 'up', color: '#3b82f6' },
      { id: '14-3', row: 3, col: 1, direction: 'down', color: '#10b981' },
      { id: '14-4', row: 0, col: 4, direction: 'right', color: '#f59e0b' },
      { id: '14-5', row: 4, col: 0, direction: 'left', color: '#ec4899' },
      { id: '14-6', row: 1, col: 4, direction: 'up', color: '#8b5cf6' },
    ],
  },
  {
    id: 15,
    name: 'Prism Deflector',
    subtitle: 'Deflector runes turn exit rays 90° mid-flight',
    difficulty: 'hard',
    rows: 5,
    cols: 5,
    parMoves: 7,
    rewardCoins: 260,
    deflectors: [
      { row: 1, col: 3, redirectDirection: 'up' },
      { row: 3, col: 1, redirectDirection: 'down' },
    ],
    arrows: [
      // (1,1) facing right hits deflector at (1,3) which redirects ray UP!
      { id: '15-1', row: 1, col: 1, direction: 'right', color: '#06b6d4' },
      // (3,3) facing left hits deflector at (3,1) which redirects ray DOWN!
      { id: '15-2', row: 3, col: 3, direction: 'left', color: '#ec4899' },
      { id: '15-3', row: 0, col: 0, direction: 'left', color: '#10b981' },
      { id: '15-4', row: 4, col: 4, direction: 'right', color: '#f59e0b' },
      { id: '15-5', row: 2, col: 2, direction: 'up', color: '#8b5cf6' },
    ],
  },

  // ── PHASE 4: SHAPED SILHOUETTES (Cross, Diamond, Star, Heart) (Levels 16-20)
  {
    id: 16,
    name: 'The Crossway',
    subtitle: 'Plus-shaped grid: arrows outside cross wings escape instantly',
    difficulty: 'hard',
    rows: 5,
    cols: 5,
    maskShape: 'cross',
    parMoves: 8,
    rewardCoins: 280,
    arrows: [
      { id: '16-1', row: 0, col: 2, direction: 'up', color: '#06b6d4' },
      { id: '16-2', row: 4, col: 2, direction: 'down', color: '#3b82f6' },
      { id: '16-3', row: 2, col: 0, direction: 'left', color: '#10b981' },
      { id: '16-4', row: 2, col: 4, direction: 'right', color: '#ec4899' },
      { id: '16-5', row: 1, col: 2, direction: 'up', color: '#f59e0b' },
      { id: '16-6', row: 3, col: 2, direction: 'down', color: '#8b5cf6' },
      { id: '16-7', row: 2, col: 1, direction: 'left', color: '#06b6d4' },
      { id: '16-8', row: 2, col: 3, direction: 'right', color: '#3b82f6' },
    ],
  },
  {
    id: 17,
    name: 'The Diamond Vault',
    subtitle: 'Diamond silhouette with multi-cell snakes along diagonals',
    difficulty: 'hard',
    rows: 5,
    cols: 5,
    maskShape: 'diamond',
    parMoves: 8,
    rewardCoins: 300,
    arrows: [
      { id: '17-1', row: 0, col: 2, direction: 'up', color: '#06b6d4' },
      { id: '17-2', row: 4, col: 2, direction: 'down', color: '#3b82f6' },
      { id: '17-3', row: 2, col: 0, direction: 'left', color: '#10b981' },
      { id: '17-4', row: 2, col: 4, direction: 'right', color: '#ec4899' },
      { id: '17-5', row: 1, col: 1, direction: 'up-left', color: '#f59e0b' },
      { id: '17-6', row: 1, col: 3, direction: 'up-right', color: '#8b5cf6' },
      { id: '17-7', row: 3, col: 1, direction: 'down-left', color: '#10b981' },
      { id: '17-8', row: 3, col: 3, direction: 'down-right', color: '#06b6d4' },
    ],
  },
  {
    id: 18,
    name: 'Star Fortress',
    subtitle: 'Star silhouette harboring frozen core guardians',
    difficulty: 'hard',
    rows: 5,
    cols: 5,
    maskShape: 'star',
    parMoves: 9,
    rewardCoins: 320,
    arrows: [
      { id: '18-1', row: 0, col: 2, direction: 'up', color: '#06b6d4' },
      { id: '18-2', row: 4, col: 2, direction: 'down', color: '#3b82f6' },
      { id: '18-3', row: 2, col: 0, direction: 'left', color: '#10b981' },
      { id: '18-4', row: 2, col: 4, direction: 'right', color: '#ec4899' },
      { id: '18-5', row: 2, col: 2, direction: 'up', color: '#f59e0b', isFrozen: true, frozenHits: 1 },
      { id: '18-6', row: 1, col: 2, direction: 'up', color: '#8b5cf6' },
      { id: '18-7', row: 3, col: 2, direction: 'down', color: '#06b6d4' },
      { id: '18-8', row: 2, col: 1, direction: 'left', color: '#3b82f6' },
      { id: '18-9', row: 2, col: 3, direction: 'right', color: '#10b981' },
    ],
  },
  {
    id: 19,
    name: 'Heart of Arrows',
    subtitle: 'Curved heart board silhouette with pivot arrows',
    difficulty: 'expert',
    rows: 5,
    cols: 5,
    maskShape: 'heart',
    parMoves: 8,
    rewardCoins: 350,
    arrows: [
      { id: '19-1', row: 1, col: 0, direction: 'left', color: '#ec4899' },
      { id: '19-2', row: 1, col: 4, direction: 'right', color: '#ec4899' },
      { id: '19-3', row: 4, col: 2, direction: 'down', color: '#f43f5e' },
      { id: '19-4', row: 2, col: 2, direction: 'down', color: '#f59e0b', isPivot: true },
      { id: '19-5', row: 1, col: 1, direction: 'up', color: '#06b6d4' },
      { id: '19-6', row: 1, col: 3, direction: 'up', color: '#3b82f6' },
      { id: '19-7', row: 3, col: 1, direction: 'down-left', color: '#8b5cf6' },
      { id: '19-8', row: 3, col: 3, direction: 'down-right', color: '#10b981' },
    ],
  },
  {
    id: 20,
    name: 'Glacial Pivot',
    subtitle: 'Shatter ice and rotate pivots in synchronized order',
    difficulty: 'expert',
    rows: 5,
    cols: 5,
    parMoves: 10,
    rewardCoins: 380,
    arrows: [
      { id: '20-1', row: 1, col: 1, direction: 'right', color: '#06b6d4', isFrozen: true, frozenHits: 1 },
      { id: '20-2', row: 1, col: 3, direction: 'down', color: '#f59e0b', isPivot: true },
      { id: '20-3', row: 3, col: 3, direction: 'left', color: '#3b82f6', isFrozen: true, frozenHits: 1 },
      { id: '20-4', row: 3, col: 1, direction: 'up', color: '#f59e0b', isPivot: true },
      { id: '20-5', row: 0, col: 1, direction: 'up', color: '#10b981' },
      { id: '20-6', row: 1, col: 4, direction: 'right', color: '#ec4899' },
      { id: '20-7', row: 4, col: 3, direction: 'down', color: '#8b5cf6' },
      { id: '20-8', row: 3, col: 0, direction: 'left', color: '#06b6d4' },
    ],
  },

  // ── PHASE 5: GRANDMASTER COMBINATION PUZZLES (Levels 21-25) ─────────────
  {
    id: 21,
    name: 'Serpent Labyrinth',
    subtitle: 'Multi-segment snake polylines winding around each other',
    difficulty: 'expert',
    rows: 5,
    cols: 5,
    parMoves: 9,
    rewardCoins: 420,
    arrows: [
      // Snake 1 (length 3 L): head (0,1) up, body (1,1)-(1,2)
      {
        id: '21-1',
        direction: 'up',
        head: { row: 0, col: 1 },
        occupiedCells: [{ row: 0, col: 1 }, { row: 1, col: 1 }, { row: 1, col: 2 }],
        color: '#06b6d4',
      },
      // Snake 2 (length 3 L): head (4,3) down, body (3,3)-(3,2)
      {
        id: '21-2',
        direction: 'down',
        head: { row: 4, col: 3 },
        occupiedCells: [{ row: 4, col: 3 }, { row: 3, col: 3 }, { row: 3, col: 2 }],
        color: '#ec4899',
      },
      // Snake 3: length 2
      {
        id: '21-3',
        direction: 'left',
        head: { row: 2, col: 0 },
        occupiedCells: [{ row: 2, col: 0 }, { row: 2, col: 1 }],
        color: '#10b981',
      },
      // Snake 4: length 2
      {
        id: '21-4',
        direction: 'right',
        head: { row: 2, col: 4 },
        occupiedCells: [{ row: 2, col: 4 }, { row: 2, col: 3 }],
        color: '#f59e0b',
      },
      { id: '21-5', row: 0, col: 0, direction: 'left', color: '#8b5cf6' },
      { id: '21-6', row: 0, col: 4, direction: 'right', color: '#3b82f6' },
      { id: '21-7', row: 4, col: 0, direction: 'left', color: '#06b6d4' },
      { id: '21-8', row: 4, col: 4, direction: 'right', color: '#10b981' },
    ],
  },
  {
    id: 22,
    name: 'Sub-Zero Siege',
    subtitle: 'Twin bombs detonate ice walls to free corner serpents',
    difficulty: 'expert',
    rows: 6,
    cols: 6,
    parMoves: 10,
    rewardCoins: 450,
    arrows: [
      { id: '22-bomb1', row: 1, col: 1, direction: 'up', color: '#f43f5e', isBomb: true },
      { id: '22-bomb2', row: 4, col: 4, direction: 'down', color: '#f43f5e', isBomb: true },
      { id: '22-1', row: 0, col: 1, direction: 'up', color: '#06b6d4', isFrozen: true, frozenHits: 2 },
      { id: '22-2', row: 5, col: 4, direction: 'down', color: '#3b82f6', isFrozen: true, frozenHits: 2 },
      { id: '22-3', row: 1, col: 0, direction: 'left', color: '#10b981' },
      { id: '22-4', row: 4, col: 5, direction: 'right', color: '#ec4899' },
      { id: '22-5', row: 2, col: 3, direction: 'right', color: '#f59e0b' },
      { id: '22-6', row: 3, col: 2, direction: 'left', color: '#8b5cf6' },
      { id: '22-7', row: 0, col: 5, direction: 'right', color: '#06b6d4' },
      { id: '22-8', row: 5, col: 0, direction: 'left', color: '#10b981' },
    ],
  },
  {
    id: 23,
    name: 'Vortex Nexus',
    subtitle: 'Pivots and deflector prisms intertwined in harmony',
    difficulty: 'expert',
    rows: 5,
    cols: 5,
    parMoves: 9,
    rewardCoins: 480,
    deflectors: [
      { row: 0, col: 4, redirectDirection: 'down' },
      { row: 4, col: 0, redirectDirection: 'up' },
    ],
    arrows: [
      { id: '23-1', row: 0, col: 2, direction: 'right', color: '#06b6d4' },
      { id: '23-2', row: 4, col: 2, direction: 'left', color: '#3b82f6' },
      { id: '23-3', row: 2, col: 2, direction: 'up', color: '#f59e0b', isPivot: true },
      { id: '23-4', row: 1, col: 2, direction: 'up', color: '#10b981' },
      { id: '23-5', row: 3, col: 2, direction: 'down', color: '#ec4899' },
      { id: '23-6', row: 2, col: 0, direction: 'left', color: '#8b5cf6' },
      { id: '23-7', row: 2, col: 4, direction: 'right', color: '#06b6d4' },
    ],
  },
  {
    id: 24,
    name: 'Diamond Cataclysm',
    subtitle: 'Diamond perimeter with frozen pivots guarding the apex',
    difficulty: 'master',
    rows: 5,
    cols: 5,
    maskShape: 'diamond',
    parMoves: 10,
    rewardCoins: 520,
    arrows: [
      { id: '24-1', row: 0, col: 2, direction: 'up', color: '#06b6d4' },
      { id: '24-2', row: 4, col: 2, direction: 'down', color: '#3b82f6' },
      { id: '24-3', row: 2, col: 0, direction: 'left', color: '#10b981' },
      { id: '24-4', row: 2, col: 4, direction: 'right', color: '#ec4899' },
      { id: '24-5', row: 1, col: 2, direction: 'down', color: '#f59e0b', isPivot: true },
      { id: '24-6', row: 3, col: 2, direction: 'up', color: '#f59e0b', isPivot: true },
      { id: '24-7', row: 2, col: 1, direction: 'left', color: '#8b5cf6', isFrozen: true, frozenHits: 1 },
      { id: '24-8', row: 2, col: 3, direction: 'right', color: '#06b6d4', isFrozen: true, frozenHits: 1 },
    ],
  },
  {
    id: 25,
    name: 'Grandmaster Escape',
    subtitle: 'The ultimate synthesis: snakes, ice, pivots, and bombs!',
    difficulty: 'master',
    rows: 6,
    cols: 6,
    parMoves: 12,
    rewardCoins: 600,
    arrows: [
      // Central bomb
      { id: '25-bomb', row: 2, col: 2, direction: 'up', color: '#f43f5e', isBomb: true },
      // Pivot arrow
      { id: '25-pivot', row: 3, col: 3, direction: 'left', color: '#f59e0b', isPivot: true },
      // Ice guards
      { id: '25-ice1', row: 1, col: 2, direction: 'up', color: '#06b6d4', isFrozen: true, frozenHits: 1 },
      { id: '25-ice2', row: 4, col: 3, direction: 'down', color: '#3b82f6', isFrozen: true, frozenHits: 1 },
      // Multi-segment snake (length 2)
      {
        id: '25-snake1',
        direction: 'left',
        head: { row: 0, col: 0 },
        occupiedCells: [{ row: 0, col: 0 }, { row: 0, col: 1 }],
        color: '#10b981',
      },
      // Multi-segment snake (length 2)
      {
        id: '25-snake2',
        direction: 'right',
        head: { row: 5, col: 5 },
        occupiedCells: [{ row: 5, col: 5 }, { row: 5, col: 4 }],
        color: '#ec4899',
      },
      { id: '25-1', row: 0, col: 4, direction: 'up', color: '#8b5cf6' },
      { id: '25-2', row: 5, col: 1, direction: 'down', color: '#06b6d4' },
      { id: '25-3', row: 2, col: 0, direction: 'left', color: '#3b82f6' },
      { id: '25-4', row: 3, col: 5, direction: 'right', color: '#10b981' },
      { id: '25-5', row: 1, col: 4, direction: 'right', color: '#f59e0b' },
      { id: '25-6', row: 4, col: 1, direction: 'left', color: '#ec4899' },
    ],
  },
];
